### PR TITLE
General upstream cleanup

### PR DESCRIPTION
**Pull request by grillo-delmal**
Since nijilive still doesn't have a 0.0.1 release, setting the version requirement to 0.0.0 will make it easier to setup and build.

I also removed some of the upstream code and logic that doesn't make sense in this project considering that it's opensource.
* Old tracking code that is disabled by default
* barebones optional build
* Demo mode
* Branding version

### CODE REVIEW

**Comment by r888800009** [comment]
From my experience, retaining the version number from the beginning helps prevent environmental inconsistencies. We shouldn't remove it.

**Comment by r888800009** [comment]
Instead, there is a WIP PR #7 document you can check.

**Comment by grillo-delmal** [comment]
It's just a bit more convenient, since it doesn't require to hardcode the version when doing `dub add-local` :3
That way dub is able to show the library version depending on the commit you are standing.

For example, running `dub add-local` on nijilive would return
```
Registered package: nijilive (version: 0.0.0+build.652.bd00329)
```
and it would show the version correctly when using `dub describe` or `dub list`, which I would prefer to have available for packaging purposes ^^

**Comment by grillo-delmal** [comment]
> From my experience, retaining the version number from the beginning helps prevent inconsistencies dependencies. We shouldn't remove it.

I agree when those libraries actually have versions, since they don't right now it's just an unnecessary inconvenience.

setting the dependencies to "~>0.0.0" would be more acurate too considering that's what the libraries give when importing them without version overriding

**Comment by seagetch** [comment]
@grillo-delmal I think github action have to be changed, too. and there are other PR to change gitver, maybe that must be applied first, and then need to look again about this.
current CI script set dub add-local 0.0.1 to compile nightly. so that part must be considered, too.

**Comment by seagetch** [comment]
@grillo-delmal and I'm not sure "0.0.0" can be applied to the source code repository without any tag.

**Comment by seagetch** [comment]
@grillo-delmal
Could you revert version related things to "0.0.1" once? I couldn't figure out the effect of the change yet. I prefer to merge other changes first.

**Comment by grillo-delmal** [comment]
> @grillo-delmal Could you revert version related things to "0.0.1" once? I couldn't figure out the effect of the change yet. I prefer to merge other changes first.

done :)

**Comment by grillo-delmal** [comment]
> @grillo-delmal and I'm not sure "0.0.0" can be applied to the source code repository and dub repository without any tag.

Just to be clear, setting it to `~>0.0.0` won't break the CI, since it matches `0.0.0` and `0.0.X` where `X > 0`, so even if you add the library forcing 0.0.1 it won't break anything. but it's not something critical since it's just a thing that 

> @grillo-delmal Could you revert version related things to "0.0.1" once? I couldn't figure out the effect of the change yet. I prefer to merge other changes first.

ok ^^ that part is not critical anyway :3

**Pull request merged**
