### PR TITLE
Avoid crashes when opening files that do not exist

### PR DESCRIPTION
**Pull request by r888800009**
Currently, the file history will not be updated after the file is deleted. Users may crash when opening files that do not exist. The patch adds a check.
```
std.file.FileException@std/file.d(372): /Users/user/notexistfile.inx: No such file or directory
----------------
??:? object.Throwable.TraceInfo core.runtime.defaultTraceHandler(void*) [0xxxxxxxxxx]
/Users/user/nijilive/source/nijilive/fmt/package.d:36 nijigenerate.ext.ExPuppet nijilive.fmt.inLoadPuppet!(nijigenerate.ext.ExPuppet).inLoadPuppet(immutable(char)[]) [0xxxxxxxxxx]
/Users/user/nijigenerate/source/nijigenerate/package.d:239 void nijigenerate.incOpenProject!(true).incOpenProject(immutable(char)[], immutable(char)[]) [0xxxxxxxxxx]
/Users/user/nijigenerate/source/nijigenerate/package.d:220 void nijigenerate.incOpenProject!(true).incOpenProject(immutable(char)[]) [0xxxxxxxxxx]
/Users/user/nijigenerate/source/nijigenerate/widgets/mainmenu.d:134 void nijigenerate.widgets.mainmenu.incMainMenu() [0xxxxxxxxxx]
/Users/user/nijigenerate/source/app.d:137 void app.incUpdate() [0xxxxxxxxxx]
/Users/user/nijigenerate/source/app.d:103 _Dmain [0xxxxxxxxxx]
```

### CODE REVIEW

**Comment by r888800009** [comment]
By the way, the try block below is commented out. I'm not sure if it was intended to assert a failure or for some other reason, so I left the comments as they were.

https://github.com/nijigenerate/nijigenerate/blob/5672d3d9432c06dd6368c82ff4ec7d51eb6aec0e/source/nijigenerate/package.d#L243-L257

**Comment by seagetch** [comment]
I once commented out that because it doesn't give a detailed information when serialization problem throws the exception.
It's debugging purpose, and should uncomment again.
At the same time, application should leave more detailed information on failure for debugging.

**Comment by seagetch** [comment]
> I think since the path has already been checked, any subsequent exceptions should be unusual. Maybe a try-catch block isn't necessary?
> 
> We can leave a crash dump on the user side or debug the debug version.

There may be a lot of runtime error. e.g. network error on shared file system etc.
I think crash with them is not appropriate.

**Comment by r888800009** [comment]
`incOpenProject()` now utilizes FileException to handle I/O errors. Some try-catch blocks have been removed to avoid obscuring other types of exceptions.

**Pull request merged**
